Repository cvlab-ai/polish_banknotes, pull requests merged in 2023-04, with the labels that each got.

#61 Mocky settings.
  Android/PolishBanknotesApp/app/build.gradle
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/MainActivity.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/accesability/Beeper.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/fragments/CameraFragment.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/fragments/SettingsFragment.kt
  Android/PolishBanknotesApp/app/src/client/res/layout/activity_main.xml
  Android/PolishBanknotesApp/app/src/client/res/layout/fragment_camera.xml
  Android/PolishBanknotesApp/app/src/client/res/menu/activity_main_menu.xml
  Android/PolishBanknotesApp/app/src/client/res/menu/settings_fragment_menu.xml
  Android/PolishBanknotesApp/app/src/client/res/navigation/nav_graph.xml
  Android/PolishBanknotesApp/app/src/client/res/values/arrays.xml
  Android/PolishBanknotesApp/app/src/client/res/values/strings.xml
  Android/PolishBanknotesApp/app/src/client/res/xml/root_preferences.xml
  Android/PolishBanknotesApp/app/src/main/AndroidManifest.xml
  Android/PolishBanknotesApp/app/src/main/res/drawable/ic_baseline_arrow_back_24.xml
  Android/PolishBanknotesApp/app/src/main/res/drawable/ic_baseline_settings_24.xml
Labels: enhancement

#63 Changed vibrating on older devices.
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/accesability/Haptizer.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/fragments/CameraFragment.kt
Labels: bug

#69 Inner merge
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/MainActivity.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/fragments/CameraFragment.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/fragments/SettingsFragment.kt
  Android/PolishBanknotesApp/app/src/client/res/layout/activity_main.xml
  Android/PolishBanknotesApp/app/src/client/res/menu/activity_main_menu.xml
  Android/PolishBanknotesApp/app/src/client/res/values/arrays.xml
  Android/PolishBanknotesApp/app/src/client/res/values/strings.xml
  Android/PolishBanknotesApp/app/src/client/res/xml/root_preferences.xml
  Android/PolishBanknotesApp/app/src/main/res/drawable/ic_baseline_sensors_24.xml
Labels: enhancement

#70 Refactor services init.
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/MainActivity.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/accessability/Beeper.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/accessability/Haptizer.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/accessability/TalkBackSpeaker.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/fragments/CameraFragment.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/fragments/SettingsFragment.kt
  Android/PolishBanknotesApp/app/src/client/res/layout/activity_main.xml
  Android/PolishBanknotesApp/app/src/client/res/menu/activity_main_menu.xml
  Android/PolishBanknotesApp/app/src/client/res/values/arrays.xml
  Android/PolishBanknotesApp/app/src/client/res/values/strings.xml
  Android/PolishBanknotesApp/app/src/client/res/xml/root_preferences.xml
  Android/PolishBanknotesApp/app/src/main/res/drawable/ic_baseline_sensors_24.xml
Labels: enhancement

#73 Settings: label management.
  Android/PolishBanknotesApp/app/build.gradle
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/fragments/CameraFragment.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/fragments/SettingsFragment.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/settings_management/LabelManager.kt
  Android/PolishBanknotesApp/app/src/client/res/layout/activity_main.xml
  Android/PolishBanknotesApp/app/src/client/res/layout/fragment_camera.xml
  Android/PolishBanknotesApp/app/src/client/res/values/arrays.xml
  Android/PolishBanknotesApp/app/src/client/res/values/colors.xml
  Android/PolishBanknotesApp/app/src/client/res/values/dimens.xml
  Android/PolishBanknotesApp/app/src/client/res/values/strings.xml
  Android/PolishBanknotesApp/app/src/client/res/xml/root_preferences.xml
  Android/PolishBanknotesApp/app/src/main/res/drawable/ic_baseline_font_download_24.xml
Labels: enhancement

#74 Moved torch handling and changed way of calculating brightness
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/MainActivity.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/fragments/CameraFragment.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/sensors/TorchManager.kt
  Android/PolishBanknotesApp/app/src/dev/java/pg/eti/project/polishbanknotes/MainActivity.kt
  Android/PolishBanknotesApp/app/src/dev/java/pg/eti/project/polishbanknotes/fragments/CameraFragment.kt
  Android/PolishBanknotesApp/app/src/dev/java/pg/eti/project/polishbanknotes/sensors/TorchManager.kt
Labels: enhancement

#76 75: Secure app.
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/ImageClassifierHelper.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/fragments/CameraFragment.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/sensors/TorchManager.kt
  Android/PolishBanknotesApp/app/src/client/res/menu/activity_main_menu.xml
Labels: bug

#78 Added english as backup.
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/ImageClassifierHelper.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/accessability/TalkBackSpeaker.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/fragments/CameraFragment.kt
  Android/PolishBanknotesApp/app/src/dev/java/pg/eti/project/polishbanknotes/MainActivity.kt
Labels: bug

#80 Settings: changes in label seekbars.
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/fragments/CameraFragment.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/fragments/SettingsFragment.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/settings_management/LabelManager.kt
  Android/PolishBanknotesApp/app/src/client/res/values/dimens.xml
  Android/PolishBanknotesApp/app/src/client/res/values/strings.xml
  Android/PolishBanknotesApp/app/src/client/res/xml/root_preferences.xml
Labels: enhancement

#82 Settings: added Torch on/off.
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/fragments/CameraFragment.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/sensors/TorchManager.kt
  Android/PolishBanknotesApp/app/src/client/res/values/arrays.xml
  Android/PolishBanknotesApp/app/src/client/res/xml/root_preferences.xml
Labels: enhancement

#89 Icon, settings, accessibility, todos, try-catches, name.
  Android/PolishBanknotesApp/app/src/client/ic_app_icon-playstore.png
  Android/PolishBanknotesApp/app/src/client/ic_launcher-playstore.png
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/ImageClassifierHelper.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/MainActivity.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/accessibility/Haptizer.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/fragments/CameraFragment.kt
  Android/PolishBanknotesApp/app/src/client/res/drawable/ic_launcher_background.xml
  Android/PolishBanknotesApp/app/src/client/res/layout/fragment_camera.xml
  Android/PolishBanknotesApp/app/src/client/res/menu/activity_main_menu.xml
  Android/PolishBanknotesApp/app/src/client/res/menu/settings_fragment_menu.xml
  Android/PolishBanknotesApp/app/src/client/res/mipmap-anydpi-v26/ic_app_icon.xml
  Android/PolishBanknotesApp/app/src/client/res/mipmap-anydpi-v26/ic_app_icon_round.xml
  Android/PolishBanknotesApp/app/src/client/res/mipmap-anydpi-v26/ic_launcher.xml
  Android/PolishBanknotesApp/app/src/client/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Android/PolishBanknotesApp/app/src/client/res/mipmap-hdpi/ic_app_icon.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-hdpi/ic_app_icon_foreground.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-hdpi/ic_app_icon_round.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-hdpi/ic_launcher.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-hdpi/ic_launcher_foreground.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-hdpi/ic_launcher_round.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-mdpi/ic_app_icon.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-mdpi/ic_app_icon_foreground.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-mdpi/ic_app_icon_round.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-mdpi/ic_launcher.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-mdpi/ic_launcher_foreground.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-mdpi/ic_launcher_round.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-xhdpi/ic_app_icon.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-xhdpi/ic_app_icon_foreground.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-xhdpi/ic_app_icon_round.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-xhdpi/ic_launcher.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-xhdpi/ic_launcher_foreground.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-xhdpi/ic_launcher_round.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-xxhdpi/ic_app_icon.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-xxhdpi/ic_app_icon_foreground.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-xxhdpi/ic_app_icon_round.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-xxhdpi/ic_launcher.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-xxhdpi/ic_launcher_foreground.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-xxhdpi/ic_launcher_round.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-xxxhdpi/ic_app_icon.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-xxxhdpi/ic_app_icon_foreground.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-xxxhdpi/ic_app_icon_round.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-xxxhdpi/ic_launcher.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  Android/PolishBanknotesApp/app/src/client/res/mipmap-xxxhdpi/ic_launcher_round.png
  Android/PolishBanknotesApp/app/src/client/res/values/ic_app_icon_background.xml
  Android/PolishBanknotesApp/app/src/client/res/values/strings.xml
  Android/PolishBanknotesApp/app/src/client/res/xml/root_preferences.xml
  Android/PolishBanknotesApp/app/src/dev/java/pg/eti/project/polishbanknotes/fragments/CameraFragment.kt
  Android/PolishBanknotesApp/app/src/main/AndroidManifest.xml
Labels: bug, enhancement

#96 88 change method of calculating brightness
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/sensors/TorchManager.kt
Labels: enhancement

#100 Change text size.
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/fragments/CameraFragment.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/fragments/SettingsFragment.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/settings_management/LabelManager.kt
  Android/PolishBanknotesApp/app/src/client/res/layout/fragment_camera.xml
  Android/PolishBanknotesApp/app/src/client/res/menu/settings_fragment_menu.xml
  Android/PolishBanknotesApp/app/src/client/res/values/strings.xml
Labels: enhancement
