Repository cvlab-ai/polish_banknotes, pull requests merged in 2023-05, with the labels that each got.

#108 Changed beeps.
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/accessibility/Beeper.kt
Labels: enhancement

#109 Label delay removed + bug fix
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/fragments/CameraFragment.kt
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/settings_management/LabelManager.kt
Labels: enhancement

#112 Update README.md
  README.md
Labels: documentation, enhancement

#115 Fix label allowance
  Android/PolishBanknotesApp/app/src/client/java/pg/eti/project/polishbanknotes/fragments/CameraFragment.kt
Labels: bug
